var cateogry=require('../bin/model/cateogry_model');
var express=require('express');
var router=express.Router();
router.get('/:cat_id?',function(req,res,next){
    if(req.params.cat_id){
        cateogry.getCateogryById(req.params.cat_id,function(err,rows){
            if(err)
            {
                res.json(err)
            }
            else
            {
                res.json(rows)
            }
        })
    }
    else{
    cateogry.getAllTask(function(err,rows)
        {
            if(err)
            {
                res.json(err)
            }
            else{
                res.json(rows)
            }
        });
    }

});
router.post('/',function(req,res,next){
    cateogry.addTask(req.body,function(err,rows){
        if(err)
        {
            res.json(err)
        }
        else{
            res.json(rows)
        }
    });
});
router.delete('/:cat_id',function(req,res,next){
    cateogry.deleteTask(req.params.cat_id,function(err,rows){
        if(err)
        {
            res.json(err)
        }
        else{
            res.json(rows)
        }
    });
});
router.put('/:cat_id',function(req,res,next){
    cateogry.updateTask(req.body,req.params.cat_id,function(err,rows){
    if(err)
    {
        res.json(err)
    }
    else{
        res.json(rows)
    }
});
});
module.exports=router;